### ISSUE TITLE
Shutter status is not displayed correctly

### ISSUE THREAD

**Issue by LuiTK** [FreshlyBrewedCode/hacs-homee#20]
In cover.py the following line should be corrected:
    @property
    def is_closed(self):
        """Return the state of the cover."""
        return True if self.attribute(AttributeType.POSITION) == **_100_** else False

**Comment by FreshlyBrewedCode** [comment]
There is no way for me to verify this. Do you have multiple devices where the state is displayed incorrectly? Or do you know if this attribute is documented anywhere?

Maybe @Stklingner could also confirm if this is an error that needs to be corrected (because he implemented the cover component).
https://github.com/FreshlyBrewedCode/hacs-homee/blob/f639ec424cf59930b0a2cc84db8b8fff70e728ec/custom_components/homee/cover.py#L102-L105

**Comment by LuiTK** [comment]
All my shutters have always shown the status 'opened' regardless of the position. I cannot provide concrete documentation. In the forums as well as in my position attribute the value range is between 0=open and 100=closed.
The code lines
@property
    def current_cover_position(self):
        """Return the cover's position"""
        return 100 - self.attribute(AttributeType.POSITION)
and my customization confirms my assumption.
This changes the status to closed as soon as the position 100 is reached.

**Comment by FreshlyBrewedCode** [comment]
Ok, thanks for the explanation. I will push a fix with your suggestion. If there are still problems in the future we can reopen this issue.

**Comment by LuiTK** [comment]
homee integration updated. Works - thank you

**Comment by Stklingner** [comment]
Sorry for the late reply guys, good job - I'll have a look as well (mine work fine but I use my own dev branch currently)
